### ISSUE TITLE
How the wintun-wrapper header created

### ISSUE THREAD

**Issue by taikulawo** [nulldotblack/wintun#1]
I'm trying to generate rust binding for wintun.

It's good for me find this project finally.

I have a question. How you generate the `wintun-wrapper.h` file. On the top of file, It said `Manually generated file from wintun documentation to tune what bindgen generates`. 

Is that copying from following headers, finding type that we need and put it into `wintun-wrapper.h` manually ? or just using some automated tool to do that?

```
#include <windows.h>
#include <ipexport.h>
#include <ifdef.h>
```

Thank you :)

**Comment by TroyNeubauer** [comment]
Thanks for the question! I manually copied the definitions from https://git.zx2c4.com/wintun/about/ and the only types that the wintun functions required from headers you mentioned. Then I ran `wintun_raw.rs` to generate `wintun-wrapper.h`. The rest of the code inside /src/ wraps the C-API with rust types and rust functions. Because wintun's API is very stable I don't anticipate needing to change wintun-wrapper.h or re-run bindgen in the near future.
If your project uses cargo, this crate is already on crates.io with the entire public API fully documented so you don't have to mess around with running bindgen yourself:
https://docs.rs/wintun/0.1.3/wintun/

I'll update the readme soon to make this more clear to users along with some badges to spruce things up.

**Comment by TroyNeubauer** [comment]
Since 0.2.0: #4, `wintun_raw` is generated by using the header file directly and a sneaky trick. A second file `wintun/wintun_functions.h` whose content is: 
```C
#include "wintun.h"

WINTUN_CREATE_ADAPTER_FUNC WintunCreateAdapter;
WINTUN_CLOSE_ADAPTER_FUNC WintunCloseAdapter;
WINTUN_OPEN_ADAPTER_FUNC WintunOpenAdapter;
WINTUN_GET_ADAPTER_LUID_FUNC WintunGetAdapterLUID;
WINTUN_GET_RUNNING_DRIVER_VERSION_FUNC WintunGetRunningDriverVersion;
WINTUN_DELETE_DRIVER_FUNC WintunDeleteDriver;
WINTUN_SET_LOGGER_FUNC WintunSetLogger;
WINTUN_START_SESSION_FUNC WintunStartSession;
WINTUN_END_SESSION_FUNC WintunEndSession;
WINTUN_GET_READ_WAIT_EVENT_FUNC WintunGetReadWaitEvent;
WINTUN_RECEIVE_PACKET_FUNC WintunReceivePacket;
WINTUN_RELEASE_RECEIVE_PACKET_FUNC WintunReleaseReceivePacket;
WINTUN_ALLOCATE_SEND_PACKET_FUNC WintunAllocateSendPacket;
WINTUN_SEND_PACKET_FUNC WintunSendPacket;
```
is passed to bindgen. That way the rust bindings are made directly from the exact `wintun.h` header file
